### ISSUE TITLE
install requires redis

### ISSUE THREAD

**Issue by RightSexyOrc** [GobyWallet/openapi#2]
uvicorn openapi:app

...site-packages/aioredis/connection.py", line 656, in connect
    raise ConnectionError(self._error_message(e))
aioredis.exceptions.ConnectionError: Error 111 connecting to localhost:6379. 111.

ERROR:    Application startup failed. Exiting.

**Comment by dimitrysuen** [comment]
Hi, we have removed Redis dependency.
